### ISSUE TITLE
Error when using GML driver

### ISSUE THREAD

**Issue by meyer1994** [RemotePixel/amazonlinux#11]
I am having problems when trying to use `gml` drivers for OGR. It seems that this build does not include Expat or Xerces. See the following error when running `ogrinfo` into a sample file from Sentinel 2:

```bash
$ curl -s https://pastebin.com/raw/DWfrMySu > out.gml
$ ogrinfo out.gml 
ERROR 1: Unable to create Xerces C++ or Expat based GML reader, Xerces or Expat support not configured into GDAL/OGR.
ERROR 1: File out.gml appears to be GML but the GML reader can't
be instantiated, likely because Xerces or Expat support was
not configured in.
FAILURE:
Unable to open datasource `out.gml' with the following drivers.
  -> PDS4
  -> JP2OpenJPEG
  -> PDF
  -> MBTiles
  -> EEDA
  -> ESRI Shapefile
...
```

This was tested in both versions, 2.4 and 3.0.

After checking the dockerfiles, in both versions, 2.4 and 3.0, I saw that gdal was built explicitly without both libraries.

```dockerfile
RUN cd /tmp/gdal \
      ...
      --without-expat \
      ...
      --without-xerces \
      ...
```

Is there a reason for it? I know that the intetion of this repo is to be a _lightweight_  build. But it seems weird for me. For example, Sentinel-2 has all its masks stored in GML format in the [open registry](https://registry.opendata.aws/sentinel-2/).

Would it be possible to include, at least, one of them to the build?

Thanks in advance.

**Comment by vincentsarago** [comment]
Hi @meyer1994, Thanks for this issue. 
I'm totally happy to review any PR if you'd like to add this driver!

**Comment by meyer1994** [comment]
No worries. I am still testing solutions. When I am certain I will happily do a PR.

**Comment by meyer1994** [comment]
Done #12
