### ISSUE TITLE
Using GDAL 3.1Dev

### ISSUE THREAD

**Issue by TimJMartin** [RemotePixel/amazonlinux#15]
Hi @vincentsarago this repo is awesome, thanks v much.

After reading some of your COG medium posts and trying a few things out I would really like to use GDAL3.1's new COG driver to get Lambda to generate COGs for every file I load into an S3 bucket.

You Dockerfiles uses https://github.com/OSGeo/gdal/archive/ but there doesn't seem to be one for the latest dev version.

Do you know a way or point me in the direction how I could modify your Dockerfile to use the dev version?

Many thank for your help

**Comment by vincentsarago** [comment]
@TimJMartin thanks for opening this issue, adding `gdalmaster` is part of my `TODO` list, but since https://github.com/RemotePixel/amazonlinux/issues/10 I'm a kind hesitant to add it. 

Also there is a problem of recency and update, because there is no official pre-release of GDAL 3.1 we will have to decide how often we want to update the docker image...

**Comment by TimJMartin** [comment]
@vincentsarago ok. So would you recommend using rasterio to create the COGs until 3.1 becomes the current version?

**Comment by vincentsarago** [comment]
oh that's a different topic! the problem mentioned in #10 is when trying to do dynamic tiling using COG with gdal 3.0. 

About creating COG, you can use gdal3.1 and new COG driver but you'll have to understand thaat only libraries built against GDAL 3.1 and new libtiff will be able to fully take the advantage of the change in the specification.

My personal opinion is to wait until GDAL 3.1 is released before using the new COG driver in production.

**Comment by TimJMartin** [comment]
@vincentsarago great advice thanks. I will close this as you said you already have it on your TODO list.
