### ISSUE TITLE
PostgreSQL driver not found

### ISSUE THREAD

**Issue by stdmn** [RemotePixel/amazonlinux#23]
I recently stumbled across this repo and it's exactly what I've been looking for to use ogr2ogr with Lambda. I've been able to get it running for some relatively conventional use cases (including reading a file in directly from an S3 bucket) but it looks like the Postgres driver isn't included in this build. Any tips on the best way to include this? I've been using the us-east-1 Python 3.7 layer

Here's my function:

```
def lambda_handler(event, context):
        # s3 upload triggers function
        srcBucket = os.environ['STORAGE_BUCKETNAME']   # get bucket from env
        keyURI = event['Records'][0]['s3']['object']['key']   # get key from event
        srcKey = unquote(keyURI)
        filename = keyURI.split('/')[-1]
        path = '/vsis3/'+srcBucket+'/'+srcKey   # create s3 input url for ogr2ogr
        commands = [
           'ogr2ogr', '-f', '"PostgreSQL"', 'PG:"host=<HOST> user=<USER> dbname=<DB> password=<PW>"', path
        ]
        subprocess.check_output(commands)
     
    return {
        'statusCode': 200,
        'body': json.dumps('Success)
    }
```

Specific error message is: `Unable to find driver 'PostgreSQL'.`

If I can get this to work, it would be phenomenal

**Comment by vincentsarago** [comment]
👋 @stdmn thanks for openning this issue. 
We didn't add PostgresSQL driver to the GDAL install but this might be something we can add. 
Basically we need to install/compile PostgreSQL somewhere around https://github.com/RemotePixel/amazonlinux/blob/master/base/gdal3.0/Dockerfile#L75
and then add `--with-pg=YES` to gdal config.

I may have time during the holiday to look deeply into this

**Comment by stdmn** [comment]
That would be highly appreciated!

**Comment by vincentsarago** [comment]
fixed by https://github.com/RemotePixel/amazonlinux/commit/d7f1f5c656145d4ffd13e283a50bb9973c4b8ce3
